"""Portfolio Intelligence domain package."""

from .attribution import calculate_attribution
from .context import (
    ContextClassification,
    ContextConfig,
    MovementContext,
    compare_latest_context,
)
from .evaluation import (
    BinaryClassificationMetrics,
    ExplanationQualityMetrics,
    binary_classification_metrics,
    evaluate_claim_support,
    evaluate_explanation,
    precision_at_k,
    temporal_validity_rate,
)
from .events import InvestigationEvent, InvestigationEventConfig, build_investigation_event
from .evidence import (
    EvidenceItem,
    EvidenceRankingConfig,
    EvidenceTiming,
    EvidenceWindow,
    InMemoryNewsProvider,
    NewsProvider,
    RankedEvidence,
    classify_evidence_timing,
    rank_evidence,
)
from .explanation import (
    ExplanationConfidence,
    ExplanationPolicy,
    ExplanationReadiness,
    GroundedClaim,
    GroundedExplanation,
    assess_explanation_readiness,
    build_abstention,
    build_grounded_explanation,
)
from .live_portfolio import (
    DEFAULT_CONTEXT_DEFINITIONS,
    ContextDefinition,
    LiveEvidenceAssessment,
    LiveHoldingAnalysis,
    LiveInvestigationDetail,
    LivePortfolioAnalysis,
    PortfolioPositionInput,
    analyze_live_portfolio,
    build_live_evidence_assessment,
    build_live_investigation_detail,
)
from .market_data import (
    InMemoryMarketDataProvider,
    MarketDataProvider,
    MarketDataProviderError,
    PricePoint,
    PriceSeries,
)
from .models import Holding, HoldingPerformance, PortfolioAttribution, PortfolioSnapshot
from .movement import (
    DailyReturn,
    MovementDetectorConfig,
    MovementSignal,
    calculate_daily_returns,
    detect_latest_movement,
)
from .providers import (
    AlphaVantageNewsError,
    AlphaVantageNewsProvider,
    YFinanceMarketDataProvider,
)

__all__ = [
    "Holding",
    "HoldingPerformance",
    "ContextClassification",
    "ContextConfig",
    "ContextDefinition",
    "DEFAULT_CONTEXT_DEFINITIONS",
    "EvidenceItem",
    "EvidenceRankingConfig",
    "EvidenceTiming",
    "EvidenceWindow",
    "BinaryClassificationMetrics",
    "ExplanationConfidence",
    "ExplanationPolicy",
    "ExplanationReadiness",
    "ExplanationQualityMetrics",
    "GroundedClaim",
    "GroundedExplanation",
    "InMemoryMarketDataProvider",
    "InvestigationEvent",
    "InvestigationEventConfig",
    "LiveHoldingAnalysis",
    "LiveEvidenceAssessment",
    "LiveInvestigationDetail",
    "LivePortfolioAnalysis",
    "InMemoryNewsProvider",
    "MarketDataProvider",
    "MarketDataProviderError",
    "MovementDetectorConfig",
    "MovementContext",
    "MovementSignal",
    "NewsProvider",
    "PortfolioAttribution",
    "PortfolioPositionInput",
    "PortfolioSnapshot",
    "PricePoint",
    "PriceSeries",
    "RankedEvidence",
    "calculate_attribution",
    "assess_explanation_readiness",
    "analyze_live_portfolio",
    "AlphaVantageNewsError",
    "AlphaVantageNewsProvider",
    "binary_classification_metrics",
    "build_abstention",
    "build_grounded_explanation",
    "build_live_investigation_detail",
    "build_live_evidence_assessment",
    "evaluate_claim_support",
    "evaluate_explanation",
    "calculate_daily_returns",
    "classify_evidence_timing",
    "compare_latest_context",
    "build_investigation_event",
    "detect_latest_movement",
    "rank_evidence",
    "precision_at_k",
    "temporal_validity_rate",
    "YFinanceMarketDataProvider",
    "DailyReturn",
]
